"""cours

Revision ID: 03e3b17836aa
Revises: d830ffb454e8
Create Date: 2026-09-09 00:12:02.770034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e3b17836aa'
down_revision: Union[str, Sequence[str], None] = 'd830ffb454e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('jour', sa.String(length=20), nullable=True),
    sa.Column('heure_debut', sa.String(length=10), nullable=True),
    sa.Column('heure_fin', sa.String(length=10), nullable=True),
    sa.Column('salle', sa.String(length=50), nullable=True),
    sa.Column('descriptif', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ecole_id'], ['ecoles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cours_ecole_id'), 'cours', ['ecole_id'], unique=False)
    op.create_table('cours_professeurs',
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('professeur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('cours_id', 'professeur_id')
    )
    op.create_table('eleves_cours',
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('eleve_id', 'cours_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eleves_cours')
    op.drop_table('cours_professeurs')
    op.drop_index(op.f('ix_cours_ecole_id'), table_name='cours')
    op.drop_table('cours')
    # ### end Alembic commands ###
