"""ordre des cours

Revision ID: 322661184736
Revises: cdd23f51a937
Create Date: 2026-09-15 10:17:30.858855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322661184736'
down_revision: Union[str, Sequence[str], None] = 'cdd23f51a937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Regroupé par famille (Éveil, puis tous les Classique/Pointes, puis
# tous les Jazz, puis tous les Street, puis tous les Contempo) — jamais
# alphabétique (voir models.py:Cours.ordre et
# frontend-inscription/src/coursPublics.js, même ordre côté formulaire
# public). Uniquement les 17 noms de cours connus (voir
# eleves/import_excel.py) — un cours au nom différent garde ordre=0
# (valeur par défaut ci-dessous), à corriger à la main si besoin.
_ORDRE_PAR_NOM = {
    "Éveil": 1,
    "Class Ini": 2,
    "Class Moy": 3,
    "Class Inter": 4,
    "Class AV": 5,
    "Pointes inter": 6,
    "Pointes AV": 7,
    "Jazz Ini": 8,
    "Jazz Moy": 9,
    "Jazz Junior": 10,
    "Jazz Inter": 11,
    "Jazz AV": 12,
    "Street Moyen": 13,
    "Street Junior Inter": 14,
    "Contempo Junior": 15,
    "Contempo Inter avance": 16,
    "Contempo Adulte": 17,
}


def upgrade() -> None:
    """Upgrade schema."""
    # `server_default='0'` : SQLite refuse une colonne NOT NULL sans
    # défaut si la table a déjà des lignes (même patron que
    # 4ce2d0b51907_helloasso_paiement_echeances.py).
    op.add_column('cours', sa.Column('ordre', sa.Integer(), nullable=False, server_default='0'))

    cours = sa.table("cours", sa.column("nom", sa.String), sa.column("ordre", sa.Integer))
    connexion = op.get_bind()
    for nom, ordre in _ORDRE_PAR_NOM.items():
        connexion.execute(cours.update().where(cours.c.nom == nom).values(ordre=ordre))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cours', 'ordre')
    # ### end Alembic commands ###
