"""presence

Revision ID: 4316476f5e1a
Revises: c9ea10b4daf0
Create Date: 2026-09-09 00:23:44.018526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4316476f5e1a'
down_revision: Union[str, Sequence[str], None] = 'c9ea10b4daf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seances_presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seances_presence_cours_id'), 'seances_presence', ['cours_id'], unique=False)
    op.create_table('presences_eleves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seance_id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['comptes.id'], ),
    sa.ForeignKeyConstraint(['seance_id'], ['seances_presence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seance_id', 'eleve_id', name='uq_presence_eleve')
    )
    op.create_index(op.f('ix_presences_eleves_eleve_id'), 'presences_eleves', ['eleve_id'], unique=False)
    op.create_index(op.f('ix_presences_eleves_seance_id'), 'presences_eleves', ['seance_id'], unique=False)
    op.create_table('presences_profs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seance_id', sa.Integer(), nullable=False),
    sa.Column('professeur_id', sa.Integer(), nullable=False),
    sa.Column('heure_debut_reelle', sa.String(length=10), nullable=True),
    sa.Column('heure_fin_reelle', sa.String(length=10), nullable=True),
    sa.Column('depassement_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professeur_id'], ['comptes.id'], ),
    sa.ForeignKeyConstraint(['seance_id'], ['seances_presence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seance_id', 'professeur_id', name='uq_presence_prof')
    )
    op.create_index(op.f('ix_presences_profs_professeur_id'), 'presences_profs', ['professeur_id'], unique=False)
    op.create_index(op.f('ix_presences_profs_seance_id'), 'presences_profs', ['seance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presences_profs_seance_id'), table_name='presences_profs')
    op.drop_index(op.f('ix_presences_profs_professeur_id'), table_name='presences_profs')
    op.drop_table('presences_profs')
    op.drop_index(op.f('ix_presences_eleves_seance_id'), table_name='presences_eleves')
    op.drop_index(op.f('ix_presences_eleves_eleve_id'), table_name='presences_eleves')
    op.drop_table('presences_eleves')
    op.drop_index(op.f('ix_seances_presence_cours_id'), table_name='seances_presence')
    op.drop_table('seances_presence')
    # ### end Alembic commands ###
