"""helloasso paiement echeances

Revision ID: 4ce2d0b51907
Revises: e74ef38ca460
Create Date: 2026-09-11 22:55:24.522688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce2d0b51907'
down_revision: Union[str, Sequence[str], None] = 'e74ef38ca460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `server_default='1'` ajouté à la main : SQLite refuse une colonne
    # NOT NULL sans défaut si la table a déjà des lignes (voir
    # inscriptions.py : 1 = paiement comptant, valeur par défaut pour
    # toute inscription existante avant cette migration).
    op.add_column(
        'inscriptions',
        sa.Column('paiement_nb_echeances', sa.Integer(), nullable=False, server_default='1'),
    )
    op.add_column('inscriptions', sa.Column('helloasso_checkout_intent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inscriptions', 'helloasso_checkout_intent_id')
    op.drop_column('inscriptions', 'paiement_nb_echeances')
    # ### end Alembic commands ###
