"""video_duree_secondes

Revision ID: 4e7b21f2c151
Revises: 71c625030189
Create Date: 2026-09-10 10:44:36.305359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7b21f2c151'
down_revision: Union[str, Sequence[str], None] = '71c625030189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('duree_secondes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'duree_secondes')
    # ### end Alembic commands ###
