"""choregraphies_videos

Revision ID: 5f0a1e0b2a58
Revises: 4316476f5e1a
Create Date: 2026-09-09 00:27:43.346521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0a1e0b2a58'
down_revision: Union[str, Sequence[str], None] = '4316476f5e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choregraphies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('horaire_repetition', sa.String(length=100), nullable=True),
    sa.Column('costume', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_choregraphies_cours_id'), 'choregraphies', ['cours_id'], unique=False)
    op.create_table('choregraphies_eleves',
    sa.Column('choregraphie_id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['choregraphie_id'], ['choregraphies.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('choregraphie_id', 'eleve_id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('choregraphie_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lien_fichier', sa.String(length=500), nullable=False),
    sa.Column('date_publication', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['choregraphie_id'], ['choregraphies.id'], ),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_choregraphie_id'), 'videos', ['choregraphie_id'], unique=False)
    op.create_index(op.f('ix_videos_cours_id'), 'videos', ['cours_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_cours_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_choregraphie_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_table('choregraphies_eleves')
    op.drop_index(op.f('ix_choregraphies_cours_id'), table_name='choregraphies')
    op.drop_table('choregraphies')
    # ### end Alembic commands ###
