"""import_excel_et_correction_email_comptes

Revision ID: 9dc96339d624
Revises: dff9361bd42c
Create Date: 2026-09-09 13:36:49.448445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc96339d624'
down_revision: Union[str, Sequence[str], None] = 'dff9361bd42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mappings_colonnes_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.Column('en_tete_excel', sa.String(length=150), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['ecole_id'], ['ecoles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecole_id', 'en_tete_excel', name='uq_mapping_colonne_ecole_entete')
    )
    op.create_index(op.f('ix_mappings_colonnes_import_ecole_id'), 'mappings_colonnes_import', ['ecole_id'], unique=False)
    # batch_alter_table : SQLite ne supporte pas ALTER de contraintes
    # directement (voir ddl/sqlite.py) — le mode batch recopie la table.
    # Portable : sur Postgres/prod, ça reste des ALTER TABLE classiques.
    with op.batch_alter_table('comptes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_compte_ecole_email', type_='unique')
        batch_op.create_index('ix_compte_ecole_email', ['ecole_id', 'email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comptes', schema=None) as batch_op:
        batch_op.drop_index('ix_compte_ecole_email')
        batch_op.create_unique_constraint('uq_compte_ecole_email', ['ecole_id', 'email'])
    op.drop_index(op.f('ix_mappings_colonnes_import_ecole_id'), table_name='mappings_colonnes_import')
    op.drop_table('mappings_colonnes_import')
    # ### end Alembic commands ###
