"""compte_code_recuperation

Revision ID: a84117654fe3
Revises: c374585ed970
Create Date: 2026-09-10 15:58:11.863775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84117654fe3'
down_revision: Union[str, Sequence[str], None] = 'c374585ed970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comptes', sa.Column('code_recuperation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comptes', 'code_recuperation')
    # ### end Alembic commands ###
