"""conversations_whatsapp

Revision ID: c374585ed970
Revises: 4e7b21f2c151
Create Date: 2026-09-10 15:04:06.215645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c374585ed970'
down_revision: Union[str, Sequence[str], None] = '4e7b21f2c151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'conversations',
        sa.Column('whatsapp_statut', sa.String(length=20), nullable=False, server_default='aucun'),
    )
    op.add_column('conversations', sa.Column('whatsapp_groupe_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'whatsapp_groupe_id')
    op.drop_column('conversations', 'whatsapp_statut')
    # ### end Alembic commands ###
