"""eleves

Revision ID: c9ea10b4daf0
Revises: 03e3b17836aa
Create Date: 2026-09-09 00:16:12.014500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ea10b4daf0'
down_revision: Union[str, Sequence[str], None] = '03e3b17836aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts_eleves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('lien', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_eleves_eleve_id'), 'contacts_eleves', ['eleve_id'], unique=False)
    op.create_table('profils_eleves',
    sa.Column('compte_id', sa.Integer(), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('traitement_medical', sa.Text(), nullable=True),
    sa.Column('informations_importantes', sa.Text(), nullable=True),
    sa.Column('statut_paiement', sa.String(length=20), nullable=False),
    sa.Column('montant_total_annee', sa.Float(), nullable=True),
    sa.Column('montant_paye', sa.Float(), nullable=False),
    sa.Column('commentaire_admin', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('compte_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profils_eleves')
    op.drop_index(op.f('ix_contacts_eleves_eleve_id'), table_name='contacts_eleves')
    op.drop_table('contacts_eleves')
    # ### end Alembic commands ###
