"""cours horaires supplementaires

Revision ID: cdd23f51a937
Revises: 4ce2d0b51907
Create Date: 2026-09-15 09:54:55.831133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd23f51a937'
down_revision: Union[str, Sequence[str], None] = '4ce2d0b51907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cours_horaires_supplementaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('jour', sa.String(length=20), nullable=False),
    sa.Column('heure_debut', sa.String(length=10), nullable=False),
    sa.Column('heure_fin', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cours_horaires_supplementaires_cours_id'), 'cours_horaires_supplementaires', ['cours_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cours_horaires_supplementaires_cours_id'), table_name='cours_horaires_supplementaires')
    op.drop_table('cours_horaires_supplementaires')
    # ### end Alembic commands ###
