"""inscriptions

Revision ID: d53fe656e230
Revises: 2b18a3523463
Create Date: 2026-09-11 19:10:11.558094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53fe656e230'
down_revision: Union[str, Sequence[str], None] = '2b18a3523463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.Column('token_public', sa.String(length=36), nullable=False),
    sa.Column('saison', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip_soumission', sa.String(length=45), nullable=True),
    sa.Column('eleve_nom', sa.String(length=150), nullable=False),
    sa.Column('eleve_prenom', sa.String(length=150), nullable=False),
    sa.Column('eleve_date_naissance', sa.Date(), nullable=False),
    sa.Column('eleve_adresse', sa.Text(), nullable=True),
    sa.Column('eleve_telephone', sa.String(length=30), nullable=True),
    sa.Column('eleve_email', sa.String(length=150), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('traitement_medical', sa.Text(), nullable=True),
    sa.Column('informations_importantes', sa.Text(), nullable=True),
    sa.Column('contact_urgence_nom', sa.String(length=150), nullable=True),
    sa.Column('contact_urgence_prenom', sa.String(length=150), nullable=True),
    sa.Column('contact_urgence_lien', sa.String(length=50), nullable=True),
    sa.Column('contact_urgence_telephone', sa.String(length=30), nullable=True),
    sa.Column('droit_image_autorise', sa.Boolean(), nullable=False),
    sa.Column('droit_image_site', sa.Boolean(), nullable=False),
    sa.Column('droit_image_reseaux', sa.Boolean(), nullable=False),
    sa.Column('droit_image_affiches', sa.Boolean(), nullable=False),
    sa.Column('reglement_lu_approuve', sa.Boolean(), nullable=False),
    sa.Column('signataire_nom', sa.String(length=150), nullable=True),
    sa.Column('moyen_paiement', sa.String(length=20), nullable=False),
    sa.Column('statut_paiement', sa.String(length=20), nullable=False),
    sa.Column('palier_tarifaire', sa.String(length=30), nullable=False),
    sa.Column('nb_cours_semaine', sa.Integer(), nullable=False),
    sa.Column('montant_adhesion', sa.Float(), nullable=False),
    sa.Column('montant_mensuel_septembre', sa.Float(), nullable=False),
    sa.Column('montant_trimestriel', sa.Float(), nullable=False),
    sa.Column('reduction_famille_appliquee', sa.Boolean(), nullable=False),
    sa.Column('alerte_palier_mixte', sa.Boolean(), nullable=False),
    sa.Column('doublon_possible', sa.Boolean(), nullable=False),
    sa.Column('pdf_dossier_chemin', sa.String(length=500), nullable=True),
    sa.Column('pdf_facture_chemin', sa.String(length=500), nullable=True),
    sa.Column('email_envoye', sa.Boolean(), nullable=False),
    sa.Column('email_erreur', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ecole_id'], ['ecoles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscriptions_ecole_id'), 'inscriptions', ['ecole_id'], unique=False)
    op.create_index(op.f('ix_inscriptions_token_public'), 'inscriptions', ['token_public'], unique=True)
    op.create_table('inscriptions_cours',
    sa.Column('inscription_id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['inscription_id'], ['inscriptions.id'], ),
    sa.PrimaryKeyConstraint('inscription_id', 'cours_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscriptions_cours')
    op.drop_index(op.f('ix_inscriptions_token_public'), table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_ecole_id'), table_name='inscriptions')
    op.drop_table('inscriptions')
    # ### end Alembic commands ###
