"""ecoles, comptes, familles

Revision ID: d830ffb454e8
Revises: 
Create Date: 2026-09-09 00:02:27.245946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd830ffb454e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('code_postal', sa.String(length=10), nullable=False),
    sa.Column('code_acces_admin', sa.String(length=50), nullable=False),
    sa.Column('code_acces_prof', sa.String(length=50), nullable=False),
    sa.Column('code_acces_eleve', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', 'code_postal', name='uq_ecole_nom_code_postal')
    )
    op.create_table('familles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecole_id'], ['ecoles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_familles_ecole_id'), 'familles', ['ecole_id'], unique=False)
    op.create_table('comptes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.Column('famille_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('hashed_password_ou_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecole_id'], ['ecoles.id'], ),
    sa.ForeignKeyConstraint(['famille_id'], ['familles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecole_id', 'email', name='uq_compte_ecole_email')
    )
    op.create_index('ix_compte_dedup', 'comptes', ['ecole_id', 'nom', 'prenom'], unique=False)
    op.create_index('ix_compte_ecole_role', 'comptes', ['ecole_id', 'role'], unique=False)
    op.create_index(op.f('ix_comptes_ecole_id'), 'comptes', ['ecole_id'], unique=False)
    op.create_index(op.f('ix_comptes_famille_id'), 'comptes', ['famille_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comptes_famille_id'), table_name='comptes')
    op.drop_index(op.f('ix_comptes_ecole_id'), table_name='comptes')
    op.drop_index('ix_compte_ecole_role', table_name='comptes')
    op.drop_index('ix_compte_dedup', table_name='comptes')
    op.drop_table('comptes')
    op.drop_index(op.f('ix_familles_ecole_id'), table_name='familles')
    op.drop_table('familles')
    op.drop_table('ecoles')
    # ### end Alembic commands ###
