"""messagerie

Revision ID: dff9361bd42c
Revises: 5f0a1e0b2a58
Create Date: 2026-09-09 09:22:43.911542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff9361bd42c'
down_revision: Union[str, Sequence[str], None] = '5f0a1e0b2a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecole_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ecole_id'], ['ecoles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_ecole_id'), 'conversations', ['ecole_id'], unique=False)
    op.create_table('conversation_membres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('membre_type', sa.String(length=20), nullable=False),
    sa.Column('membre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_membres_conversation_id'), 'conversation_membres', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('expediteur_id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['expediteur_id'], ['comptes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('message_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('destinataire_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=10), nullable=False),
    sa.Column('statut', sa.String(length=10), nullable=False),
    sa.Column('envoi_volontaire', sa.Boolean(), nullable=False),
    sa.Column('envoye_at', sa.DateTime(), nullable=False),
    sa.Column('recu_at', sa.DateTime(), nullable=True),
    sa.Column('lu_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destinataire_id'], ['comptes.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_deliveries_destinataire_id'), 'message_deliveries', ['destinataire_id'], unique=False)
    op.create_index(op.f('ix_message_deliveries_message_id'), 'message_deliveries', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_deliveries_message_id'), table_name='message_deliveries')
    op.drop_index(op.f('ix_message_deliveries_destinataire_id'), table_name='message_deliveries')
    op.drop_table('message_deliveries')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_membres_conversation_id'), table_name='conversation_membres')
    op.drop_table('conversation_membres')
    op.drop_index(op.f('ix_conversations_ecole_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
