"""photo eleve inscription

Revision ID: e74ef38ca460
Revises: d53fe656e230
Create Date: 2026-09-11 20:14:53.924233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74ef38ca460'
down_revision: Union[str, Sequence[str], None] = 'd53fe656e230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscriptions', sa.Column('eleve_photo_chemin', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inscriptions', 'eleve_photo_chemin')
    # ### end Alembic commands ###
